name: Python Package Release Test
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  test-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup dummy git user
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Checkout main and rebase
      run: |
        git checkout main
        git rebase origin/${{ github.head_ref }}
    - name: Install poetry
      run: pipx install poetry
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.8.8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "-vv --noop"